### ISSUE TITLE
undefined method `match?'

### ISSUE THREAD

**Issue by base16soft** [mobi/telephone_number#71]
Hi, 

After the update to 1.4.0, I'm getting this error:

NoMethodError: undefined method `match?' for "11986865178":String
Did you mean?  match
  from telephone_number/parser.rb:34:in `block in validate'
  from telephone_number/parser.rb:33:in `select'
  from telephone_number/parser.rb:33:in `validate'
  from telephone_number/parser.rb:12:in `valid_types'
  from telephone_number/parser.rb:16:in `valid?'
  from forwardable.rb:202:in `valid?'
  from telephone_number/formatter.rb:9:in `initialize'
  from telephone_number/number.rb:14:in `new'
  from telephone_number/number.rb:14:in `initialize'
  from telephone_number/class_methods.rb:11:in `new'
  from telephone_number/class_methods.rb:11:in `parse'
  from telephone_number/class_methods.rb:15:in `valid?'
  from telephone_number/class_methods.rb:19:in `invalid?'
  from active_model/telephone_number_validator.rb:5:in `validate_each'
  from active_model/validator.rb:167:in `block in validate'
  from active_model/validator.rb:164:in `each'
  from active_model/validator.rb:164:in `validate'

Regards,

**Comment by joshwetzel** [comment]
Hi @base16soft - which version of Ruby are you running?

**Comment by base16soft** [comment]
Hi @joshwetzel, 

I'm using 2.3.7.  Sorry, I didn't see the message:

"Now that Ruby 2.3 is officially EOL, we can begin using the match? method, which processes regex statements significantly faster than `=~`."

I'll switch back to version '1.3.4'  of the gem.

Thanks

**Comment by joshwetzel** [comment]
No worries. Thank you!
